services:
  #  mongodb:
  #    image: 'mongo:latest'
  #    environment:
  #      - 'MONGO_INITDB_DATABASE=mydatabase'
  #      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
  #      - 'MONGO_INITDB_ROOT_USERNAME=root'
  #    ports:
  #      - '27017'
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: trello-v2
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sqltest!
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d trello-v2"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: