package org.kevin.trello_v2.tasks.constants

const val MAX_BOARD_TITLE_LENGTH = 48
const val MAX_BOARD_DESCRIPTION_LENGTH = 1024

const val MAX_LIST_TITLE_LENGTH = 48
const val LIST_POSITION_INTERVAL = 1024.0

const val MAX_CARD_TITLE_LENGTH = 48
const val MAX_CARD_DESCRIPTION_LENGTH = 128
const val CARD_POSITION_INTERVAL = 1024.0